### ISSUE TITLE
Trying the precompiled binaries on my M1, getting damaged file

### ISSUE THREAD

**Issue by geekysrm** [smol-ai/menubar#1]
Here's the screenshot:
<img width="279" alt="image" src="https://github.com/smol-ai/menubar/assets/10224804/5b09ae8a-5264-4e66-a23a-9f5465fadd5c">

**Comment by geekysrm** [comment]
Building from source worked!

**Comment by powerpufffs** [comment]
same here! Works if you download source + build yourself

**Comment by sw-yx** [comment]
yeah sorry for some reason the process of uploading it to github corrupts it somehow. let me know if you have better ideas on how to do this properly

**Comment by sw-yx** [comment]
ive tried uploading non zipped files now, hopefuly this works, if anyone else knows what this problem is pls help
