### ISSUE TITLE
[Request] Enable Automatic Updates + launch on Startup

### ISSUE THREAD

**Issue by seanoliver** [smol-ai/menubar#105]
Would be nice not to have to download the latest binary after each release and have a setting where the app can update itself and/or alert you to the latest version so you can do the update.

https://www.electronjs.org/docs/latest/api/auto-updater

**Comment by swyxio** [comment]
yah

**Comment by swyxio** [comment]
use this instead https://www.electronjs.org/docs/latest/tutorial/updates#deploying-an-update-server
