### ISSUE TITLE
Problem with Google Autentication

### ISSUE THREAD

**Issue by shindiogo** [smol-ai/menubar#11]
Problem to autenticate with google. 
![image](https://github.com/smol-ai/menubar/assets/14137669/c58cdda9-bebb-42ce-a798-5fe5202ca0f8)

**Comment by swyxio** [comment]
yes this is a known issue especially for me authing with Claude. i dont know how to fix it yet.

if you're a developer, run it locally `npm run start` and see the errors.

**Comment by eathan-langford-myob** [comment]
ahhh bugger, im hitting it with Chat and Bard logins aswel, SSO for Chat and enter my email for Bard and they both end up at the same blank screen as above

**Comment by swyxio** [comment]
sorry i redirected for #201
