### ISSUE TITLE
Perplexity Login/Sign In broken

### ISSUE THREAD

**Issue by itsbrex** [smol-ai/menubar#113]
Popup modal not displaying SSO or input field like it should. Other providers unaffected.
- Tried using `TAB` + `ENTER` to see if I could trigger the login manually in case it was just hidden by the UI or something, but no luck.

`Version 0.0.16`

Current:

![image](https://github.com/smol-ai/menubar/assets/9772694/cd5a9555-229e-440d-a287-4b9b755c55c6)

Expected:

![image](https://github.com/smol-ai/menubar/assets/9772694/a240723d-ecc1-41ad-bba1-ce3168841950)

**Comment by swyxio** [comment]
cant repro right now. but thanks for filing! will take a look again when we revisit perplexity

**Comment by swyxio** [comment]
i can repro :/

**Comment by itsbrex** [comment]
@swyxio That worked! Maybe add a note in the readme about how logging into Google Bard first will auto-log you in to Perplexity for anyone having issues?

Thanks!
