### ISSUE TITLE
[Feature] make window of each URL customizable

### ISSUE THREAD

**Issue by swyxio** [smol-ai/menubar#13]
people might want to use other chat apps, eg HuggingChat, or Vicuna or OpenAssistant. 

would like to keep the number of panels to 3 (so it doesnt get too busy? but maybe we could bring it up to 6 with a second row?), but let people customize their fave chat apps for each window

however the app works by also needing a selector for the text input, and the submit button, and users aren't likely to find those on their own

easiest way is to maintain a static list of other known chat apps, that also have their input and submit selectors hardcoded.

reach goal: choices should persist esp thru version upgrades of smol menubar (so maybe store in disk?)

**Comment by swyxio** [comment]
lets also prioritize adding Bing https://twitter.com/swyx/status/1666611863734611969?s=20 @seanoliver

**Comment by seanoliver** [comment]
Nice! I'm working on setting up Hugging Chat in a local branch and I'll check out Bing too. Not sure what limitations there will be since Bing requires Edge on desktop, but I'll learn more.

Also submitted a draft here that puts each provider into its own "module" so we can more easily swap them in and out: https://github.com/smol-ai/menubar/pull/32

(This is more for directional feedback.)

**Comment by fortyplusdev** [comment]
Hi - great ideas. 2 feature request... 1- It would be great for people who don't have direct access to Anthropic yet be able to also use Poe. 2- option for the window to be pinned so it doesn't hide all the time. Lots of other great features from MenubarX & Slidebar if your looking at other options...  Thanks.

**Comment by seanoliver** [comment]
Thanks @fortyplusdev -- I'll take a look at Poe.

@swyxio Just noting here that the latest version of this PR has support for Bing: https://github.com/smol-ai/menubar/pull/32

Also lmk what you think about these providers to add next:

Bing - done in https://github.com/smol-ai/menubar/pull/32 
Perplexity
HuggingChat
Vicuna
OpenAssistant
Scite assistant
Poe

**Comment by swyxio** [comment]
some progress made here!
