### ISSUE TITLE
[FEATURE] added styling to normalize the Bard window dimensions to match the Open #helpwanted

### ISSUE THREAD

**Issue by RJSHIVA** [smol-ai/menubar#15]
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  padding: 0;
  margin: 0;
  overflow: hidden;
}

:root {
  --actual-height: calc(100vh - 12px - 80px);
}

.myarrow {
  position: relative;
  padding: 12px 0 0 0;
}

.myarrow:before {
  content: "";
  height: 0;
  width: 0;
  border-width: 0 8px 12px 8px;
  border-style: solid;
  border-color: transparent transparent white transparent;
  position: absolute;
  top: 0;
  left: 50%;
  transform: translateX(-50%);
}

@media (prefers-color-scheme: dark) {
  .myarrow:before {
    border-color: transparent transparent #343541 transparent !important;
  }
}

.page {
  background: #eeeeee;
  width: 100%;
  height: calc(100vh - 12px - 80px);
  margin-top: 12px;
  margin: 0 auto;
  position: relative;
}

.flex {
  display: flex;
  border-radius: 8px;
  overflow: hidden;
}

#form {
  height: 80px;
  width: 100%;
  display: flex;
  padding: 5px;
}

#form textarea {
  width: 100%;
  height: 80px;
  resize: none;
  overflow-y: auto;
  padding: 0 12px;
  font-size: 16px;
  outline: none;
  background-color: bisque;
  flex-grow: 1;
}

#form button {
  margin: 0 4px;
  padding: 0 12px;
}

webview {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: calc(100vh - 12px - 80px);
  display: inline-flex !important;
}

.gutter {
  background-color: #eee;
  background-repeat: no-repeat;
  background-position: 50%;
}

.gutter.gutter-horizontal {
  background-image: url("images/vertical-grip.png");
  cursor: col-resize;
}

/* Customize the bar color for Split.js */
.split .split-content::after  {
  background: linear-gradient(to right, #4c6ef5, #9059ff);
}

/* Customize the bar color on hover */
.split .split-bar:hover {
  background: linear-gradient(to right, #4c6fff, #9f59ff);
}

/* Additional Styling */

.page.darwin webview {
  width: 100%;
  height: 100%;
}

#one.split.page.darwin webview,
#two.split.page.darwin webview,
#three.split.page.darwin webview {
  width: 100%;
  height: 100%;
}

#one.split.page.darwin webview {
  width: 1194px;
}

@media screen and (max-width: 1194px) {
  #one.split.page.darwin webview {
    width: 100%;
  }
}

@media screen and (max-width: 1194px) and (orientation: landscape) {
  #one.split.page.darwin webview {
    height: 100%;
  }
}

**Comment by swyxio** [comment]
appreciate it, the styling looked weird on this one so i didnt accept it for now but would appreciate a PR and screenshots next time
