### ISSUE TITLE
running with x86 

### ISSUE THREAD

**Issue by kataqatsi** [smol-ai/menubar#17]
On x86, this line was requiring that the package be signed to run... comment out if you're trying to get something working

```diff
index.js

- require("update-electron-app")();
+ //require("update-electron-app")();
```
![Screenshot 2023-05-22 at 6 33 37 PM](https://github.com/smol-ai/menubar/assets/14959199/2b9def4f-87a2-49fd-a569-87df780eeb4e)

**Comment by yourpropertyexpert** [comment]
Alas, this hasn't been done in the "latest executable", so the only way to install on X86 seems to be to build from source :-(

**Comment by swyxio** [comment]
ok i'll address this thank you

**Comment by yourpropertyexpert** [comment]
The issue has been marked as closed, but the issue was about x86 Macs and the release that fixed it has only been made available for Arm :-(

**Comment by swyxio** [comment]
ah sorry! actually somehow the build stopped appearing for x86. mind looking into that?

**Comment by swyxio** [comment]
think i figured it out https://github.com/smol-ai/menubar/releases/tag/v0.0.6

**Comment by kataqatsi** [comment]
nice!

**Comment by yourpropertyexpert** [comment]
Thanks - I can confirm that it's now working on i386 again (and that the original issue is fixed) :-)
