### ISSUE TITLE
Getting an electron forge error

### ISSUE THREAD

**Issue by apmgd** [smol-ai/menubar#18]
I'm getting an error when running `npm build run` on my M1 Mac. Has anyone else run into this error?

`Electron forge was terminated: You must depend on "electron-prebuilt-compile" in your devDependencies`

<img width="436" alt="screenshot" src="https://github.com/smol-ai/menubar/assets/50635538/0dbc54f3-c958-4833-8282-cf9e438f89dd">

**Comment by kataqatsi** [comment]
`npm install -g electron-prebuilt-compile `

**Comment by swyxio** [comment]
fwiw i did NOT have that -g installed...

**Comment by apmgd** [comment]
@kataqatsi Looks like there isn't an arm64 version at the expected address:

`GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v8.2.0/electron-v8.2.0-darwin-arm64.zip`

But then I realized I hadn't installed the dependencies—doing that solved the issue.

**Comment by apmgd** [comment]
@kataqatsi Looks like there isn't an arm64 version at the expected address:

`GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v8.2.0/electron-v8.2.0-darwin-arm64.zip`

But then I realized I hadn't installed the dependencies—doing that solved the issue.
