### ISSUE TITLE
Copy-paste hotkeys

### ISSUE THREAD

**Issue by chriscarrollsmith** [smol-ai/menubar#20]
Something about the way you've got your hotkeys set up causes copy-paste with CTRL-C / CTRL-V to duplicate the copied text three times. This is annoying when trying to copy and paste a password into the window. I was able to bypass this problem by pasting with right-click.

My login also got rejected by OpenAI, probably because of their Auth0 CSRF token authentication system. And then they wanted me to sign in with an email link, which opened in the regular browser rather than in the menubar window.

**Comment by swyxio** [comment]
yeah i just noticed this. it's new. i'm not sure what to do about it yet... pls let me know if you figure something out

**Comment by swyxio** [comment]
i did just login to openai + bard via my google auth inside smol menubar on a completely different laptop and experienced no issues at all in case that helps anything. what auth did you use

**Comment by chriscarrollsmith** [comment]
Interesting, thanks. I did username+password, not Google. Will try Google and see if that works.

I wish I could suggest a code/design fix, but it's a tough nut to crack. There's a well-maintained Go library for OpenAI auth via cURL that might be worth looking at:

https://github.com/acheong08/OpenAIAuth

**Comment by moismat** [comment]
checked the double paste thingy, hacky fix here [#23](https://github.com/smol-ai/menubar/pull/23)

**Comment by swyxio** [comment]
we’re intercepting it with #23 for now, if anyone here knows what the “proper” fix for it is pls feel free to reopen
