### ISSUE TITLE
[Request for help] improve design

### ISSUE THREAD

**Issue by swyxio** [smol-ai/menubar#24]
the superprompt box right now is kind of an ugly yellow.

what should it look like?

note: i am getting a new design done for the icon, i know it sucks haha

**Comment by gnsaved** [comment]
Please assign me, I would love to contribute

**Comment by swyxio** [comment]
just do it :)

**Comment by RyszardRzepa** [comment]
Great project @swyxio!
I would love to have a tab bar to easily select and deselect models.
Here is my suggested UI idea for the `search bar` and `model selection tab bar`
Please let me know If you like the UI mocks so I can contribute with implementing them.

<img width="896" alt="with_tab_bar" src="https://github.com/smol-ai/menubar/assets/13038459/0622ea38-255d-425c-9633-b59eacc76607">
<img width="932" alt="Screenshot 2023-06-26 at 13 03 50" src="https://github.com/smol-ai/menubar/assets/13038459/56ff7313-c40f-41b3-bee3-ff1a5ab416cf">

**Comment by swyxio** [comment]
@RyszardRzepa that's great! yeah happy to take an implementation!

**Comment by RyszardRzepa** [comment]
I created [this](https://github.com/ryszardwhee/menubar/tree/update/textarea_styles) branch with the updated design for the textarea. I don't have contributor access to create a PR.
I discarded the idea for `tab bar` at the top. I tested it and it takes to much space. Tray settings already have this feature nad it works just fine.

<img width="1203" alt="Screenshot 2023-07-09 at 15 36 01" src="https://github.com/smol-ai/menubar/assets/13038459/160c584f-052e-4ad8-96a7-658fc2b67d77">

**Comment by swyxio** [comment]
thank you!! i dont think you need any permission to make a PR, thats how github works

**Comment by seanoliver** [comment]
Yes! This looks great — PR please!

@RyszardRzepa - You can fork the repo and submit a PR from your forked repo to our upstream repo.
