### ISSUE TITLE
Suggestions related to additional features

### ISSUE THREAD

**Issue by jakkaas** [smol-ai/menubar#25]
1. Multiple Vertical Windows each with a customizable URL, all within a main Window.
2. Each Vertical should have an + and – icon on the top right.
3. If I click the + icon, it should produce another Vertical window on the right of the existing window, in which we can input a different URL.
4. On clicking – the icon, it should close the current vertical window.
5. I should be able to create a maximum 10 numbers of vertical windows, in which we can input each window with a different URL.
6. The width of the Vertical window should be adjustable.
7. The Vertical window should be scrollable.
8. The main window containing Vertical windows should also be scrollable.

**Comment by swyxio** [comment]
10 windows is going to be sooo narrow tho lol

what would be the 10?

happy to look at a prototype

**Comment by swyxio** [comment]
that's 8. i suspect they would be too small to be useful.. try it?
