### ISSUE TITLE
Apple $99 developer fee extortion reports “smolmenubar is damaged and can’t be opened." but its actually fine

### ISSUE THREAD

**Issue by andrewsiah** [smol-ai/menubar#34]
Using macbook pro m1 pro. After downloading the arm64 binary file, and trying to open. It shows the below.
Tried deleting and reinstalling, same issue.

<img width="647" alt="Screenshot 2023-06-10 at 12 13 45 PM" src="https://github.com/smol-ai/menubar/assets/31041391/dc8b7a6a-0be2-4e3f-900e-9f190cb8aabc">

**Comment by swyxio** [comment]
thank you. this is an intermittent issue due to Apple wanting to charge $99 to publish apps.

![image](https://github.com/smol-ai/menubar/assets/6764957/d263d928-c444-48c6-a5a5-8be8ae207ae5)


i have just tried to sign up for Apple Developer, and wasted 30 minutes trying and failing for them to accept my ID. i give up. please let me know if theres some other way to do this.

**Comment by andrewsiah** [comment]
Cools, thanks!

Just wanna say cool program! It's like having three different tutors when I want to learn a concept and ask for examples from each.

**Comment by swyxio** [comment]
there's 4 now :)

**Comment by swyxio** [comment]
update: you can do this https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

To do this, [open a new Terminal window](https://www.howtogeek.com/682770/how-to-open-the-terminal-on-a-mac/) and type (or paste the following command):

```bash
xattr -d com.apple.quarantine /path/to/app.app
```

You’ll need to replace /path/to/app.app with the target location of the file you want to release from quarantine. One easy way of doing this is to [drag the file into the Terminal window](https://www.howtogeek.com/742518/use-drag-and-drop-to-speed-up-mac-terminal-commands/), right after the initial command.

**Comment by swyxio** [comment]
@andrewsiah v0.10 has notarization now https://github.com/smol-ai/menubar/releases/tag/v0.0.10 can you download and retry?

i still have not been able to figure out how to upload to testflight/mac app store.

**Comment by andrewsiah** [comment]
Cools it works, thanks!
