### ISSUE TITLE
[Looking for Contributor] New Provider: Quora Poe

### ISSUE THREAD

**Issue by swyxio** [smol-ai/menubar#38]
in #32 we added Provider modules to make it easy to add more chats. if you're new here and want an easy way to contribute, now it's a lot easier! 

please claim this and send a PR for us to review!

this work is split out from #13

**Comment by ivanleomk** [comment]
Finished it up and have added it in :) 

PR: https://github.com/smol-ai/menubar/pull/118

https://github.com/smol-ai/menubar/assets/45760326/47cc8936-8795-4b65-b1cf-a7e8c91e89c6

**Comment by ivanleomk** [comment]
Not too sure what's up with the prettier CI failing - will investigate it a bit more

**Comment by swyxio** [comment]
not your fault! github being weird
