### ISSUE TITLE
[Looking for Contributor] Vercel Chat

### ISSUE THREAD

**Issue by swyxio** [smol-ai/menubar#40]
add vercel chat provider plugin https://chat.vercel.ai/

**Comment by ivanleomk** [comment]
If no one's picked this up, I can do this sometime this week when I get the time?

**Comment by swyxio** [comment]
yup all yours

**Comment by ivanleomk** [comment]
Ok, managed to fix it up :) -> https://github.com/smol-ai/menubar/pull/117/files
