### ISSUE TITLE
Make the Superprompt bar light up when it is "in focus", darken when it is not

### ISSUE THREAD

**Issue by swyxio** [smol-ai/menubar#50]
@seanoliver an easy one to ease you back in

**Comment by seanoliver** [comment]
Oh nice idea! I'll check it out shortly!

**Comment by seanoliver** [comment]
@swyxio Hmm it looks like the `build-keys.json` and `AuthKey_QRJN4Y5JG6.p8` added in https://github.com/smol-ai/menubar/commit/0d1b1bdea20e6256200ca8ad514b8a5be1ff1b0a are required for me to build the app locally now. 

Do you know of a way to spoof this for development reasons and/or maybe you can securely share them w/ me offline?

**Comment by swyxio** [comment]
ive removed the need :)

**Comment by swyxio** [comment]
somewhat addressed  in #83
