### ISSUE TITLE
Change Default to GPT 4 on chat.openai.com

### ISSUE THREAD

**Issue by sauhaardac** [smol-ai/menubar#51]
I will try to implement this over the weekend if I have a chance, but would like to have a config option that makes GPT4 the default on chat.openai.com

Side note - enjoyed your demo yesterday @swyxio!

**Comment by swyxio** [comment]
i also want this, as well as making it switch to code interpreter by default

**Comment by swyxio** [comment]
and thanks!

**Comment by swyxio** [comment]
![image](https://github.com/smol-ai/menubar/assets/6764957/5986fd37-cdcc-4ce8-8eba-d31e5f1b0986)

i dont quite know how to do it but here's where i would maybe try to start. however i wasnt able to get it to execute yet

**Comment by swyxio** [comment]
ok this code accurately locates the button on the dom element, but idk how to make it click

![image](https://github.com/smol-ai/menubar/assets/6764957/9afa986b-a49a-4151-95ff-28c2473a80f7)

results in

![image](https://github.com/smol-ai/menubar/assets/6764957/08fe961d-e3d8-4482-a416-d7f136da7265)


```js

	static handleCss() {
		this.getWebview().addEventListener('dom-ready', () => {
      console.log('addding.....')
      this.getWebview().executeJavaScript(`
      console.log('setting timeout')
      setTimeout(function() {
        var buttons = document.getElementsByTagName('button');

for(var i = 0; i < buttons.length; i++) {
    var button = buttons[i];
    var children = button.getElementsByTagName('*');
    for(var j = 0; j < children.length; j++) {
        var child = children[j];
        if(child.textContent.includes('GPT-4')) {
            // You've found a button which has a child with 'GPT-4' in the text content
            console.log(button);
            // You can break out of the loop if you want
            button.dispatchEvent(new MouseEvent('mouseover', {
              view: window,
              bubbles: true,
              cancelable: true
            }));
            button.dispatchEvent(new MouseEvent('mousedown', {
              view: window,
              bubbles: true,
              cancelable: true
            }));
            break;
        }
    }
}
      }, 10000);
        `);
      console.log('addding..... js')
//...
```

**Comment by seanoliver** [comment]
See if this will do it? https://github.com/smol-ai/menubar/pull/52

You can just change the URL to https://chat.openai.com/?model=gpt-4

**Comment by sauhaardac** [comment]
Oh neat, y'all beat me to it 😁 

Thanks @seanoliver
