### ISSUE TITLE
Claude Manual Email / Login Code Failing

### ISSUE THREAD

**Issue by peterpme** [smol-ai/menubar#56]
Hello! Google SSO doesn't work so I tried email login and I get the code, but alas, it doesn't work. It works fine in the browser, but not here. Any ideas?

Thanks!

<img width="436" alt="image" src="https://github.com/smol-ai/menubar/assets/1211905/089b4e73-8bb3-48c7-92fa-503a83899dba">

**Comment by swyxio** [comment]
hey peter! @seanoliver had this before - make sure to type in the login code manually, because sometimes you copy the extra space they add in the email. 

long term i'd love to fix the login with google button. but i dont know electron/webview api well enough to know how to enable the popup.

**Comment by mikebracco** [comment]
@swyxio I encountered these errors on the latest version 0.17. However, I discovered that for this Claude 2 only, every character of the email or login code needs to be manually typed. When I used text expander to autocomplete my email or pasted the login code, it didn't work. It was necessary to type each character individually. But it was specific to only the Claude 2 web frame.
