### ISSUE TITLE
How to Install? 

### ISSUE THREAD

**Issue by jakkaas** [smol-ai/menubar#6]
Can you provide details instructions or easy way for a non programmer to install it.

Thanks

**Comment by sw-yx** [comment]
thanks for your interest! i may make a video for this in future, but no time right now. if anyone else sees this and can help out pls do

**Comment by swyxio** [comment]
head to https://github.com/smol-ai/menubar/releases and download either:

- [smolmenubar-0.0.6-arm64.dmg](https://github.com/smol-ai/menubar/releases/download/v0.0.6/smolmenubar-0.0.6-arm64.dmg) if you are on an M1/M2 mac
- [smolmenubar-0.0.6-x64.dmg](https://github.com/smol-ai/menubar/releases/download/v0.0.6/smolmenubar-0.0.6-x64.dmg) if on an older Intel mac

no build provided for windows yet sorry - hope somebody can come along and work on a windows build
