### ISSUE TITLE
Command + Shift + G switches desktops on macOS instead of opening on the current desktop

### ISSUE THREAD

**Issue by lsorber** [smol-ai/menubar#67]
*Problem:* if you use multiple desktops (spaces) on macOS, then pressing Command + Shift + G will switch to the desktop that you originally opened the app on.

*Expected behaviour:* I would expect the app to open on the current desktop, regardless of which desktop it was originally opened on.

*Workaround (updated):* right click on the app, select Options, and then Assign To All Desktops.

**Comment by swyxio** [comment]
thank you! i found this https://github.com/electron/electron/issues/8734 which might help

**Comment by swyxio** [comment]
can you check if this is still an issue?

**Comment by lsorber** [comment]
Seems to work now, yes, thank you! There is still some residual weird behaviour though:
- In some cases the application doesn't appear, or seems to appear behind another application.
- With multiple monitors it's not clear to me how it decides on which screen it appears.

**Comment by swyxio** [comment]
it should appear on whatever is the most recent screen but i agree its. alittle funky
