### ISSUE TITLE
Input field not automatically activated + weird Enter behavior

### ISSUE THREAD

**Issue by jacob1983** [smol-ai/menubar#71]
Problem: if you press Command + Shift + G on MacOs, the input field is not automatically activated for typing and Enter will submit.

Expected behavior: I would expect the app to automatically activate the field for typing so that I can start writing straight away after pressing Command + Shift + G. Also, I would expect Enter to result in a line break and CMD + Enter to Submit.

**Comment by swyxio** [comment]
thanks, i agree both of these are design goals

> the input field is not automatically activated 

you're right, we should fix that. cc @seanoliver 


> Also, I would expect Enter to result in a line break and CMD + Enter to Submit.

this is a setting introduced in #28 . can you double check that you turned this option off?

![image](https://github.com/smol-ai/menubar/assets/6764957/72b1adae-8f9d-4520-a1a3-31bc0582c45a)
