### ISSUE TITLE
Allow for dock icon to be hideable

### ISSUE THREAD

**Issue by adriankwil** [smol-ai/menubar#74]
The app's dock icon is always visible while the app is open. its not necessary to have both the menu bar icon and the dock icon to show together. (unless im missing a settings option?)

**Comment by swyxio** [comment]
not missing an option, no. i just didnt know how to turn it off.


menubar to the rescue:

![image](https://github.com/smol-ai/menubar/assets/6764957/ccd3bcb5-b62f-4c1a-9164-759bd235fb78)

**Comment by swyxio** [comment]
i think resolved in #80
