### ISSUE TITLE
Bug: Bing URLs and paste not working

### ISSUE THREAD

**Issue by bojdell** [smol-ai/menubar#78]
## Behavior
* Paste into bing chat does nothing
* Clicking on links does nothing:
<img width="337" alt="image" src="https://github.com/smol-ai/menubar/assets/3486165/cbd812bd-914f-430b-a472-754cd6e82b2b">

* cmd+click gives:

<img width="265" alt="image" src="https://github.com/smol-ai/menubar/assets/3486165/7b23f73f-95d6-4ae1-8cc2-b474d0be3ba1">

## Steps to reproduce
* menubar 0.0.11-x64, installed from dmg
* Ventura 13.4.1
* Logged into Bing, tried to paste and click on links in response

Will consider installing from src to use devtools

**Comment by swyxio** [comment]
thanks for the report! not tackling this right away
