### ISSUE TITLE
Shift+CMD+R, Shift+CMD+G interfere with IDE keybinds, make keybinds customizable

### ISSUE THREAD

**Issue by 0xAsynchronous** [smol-ai/menubar#84]
The current keybinds, specifically `Shift+CMD+R` and `Shift+CMD+G`, are interfering with keybinds in my IDE. This is causing unexpected behavior and disrupting my workflow. Ideally, the keybinds should be customizable, allowing users to avoid conflicts with other software, via a settings page or at least a config file.

**Comment by swyxio** [comment]
agree! happy to take a PR, i dont really know how to do this yet

**Comment by swyxio** [comment]
another approach could be to offer a few variants of activation keys other than CMD+Shift

**Comment by davej** [comment]
@swyxio I could take this on by adding a simple settings window. Not sure how to do this without a settings window. Would you be ok with me adding Svelte + Vite as build-time dependencies?

**Comment by yazinsai** [comment]
+1, also <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd> which is "search across all files" in VS Code. It's so pervasive I think it might make sense to not have it be the default shortcut.

**Comment by swyxio** [comment]
@yazinsai i hear you, @seanoliver added that one, Sean could you please propose a different shortcut? or we can drop it
