### ISSUE TITLE
[Request] Feature - UI - Allow option to toggle light/dark mode

### ISSUE THREAD

**Issue by eshack94** [smol-ai/menubar#95]
Request: allow option to toggle light/dark mode

Apologies if this is already available and I missed it. Please let me know where to find it if that's the case.

Also, I can maybe take a stab at adding this myself if someone tells me the relevant files to look at (not too familiar with the codebase).

**Comment by swyxio** [comment]
nope not available! you’ll probably want to look at the interface.js and index.js files. theres some css to make each provider dark mode as well inside the providers folder. this isnt a high priority feature for me but if you can figure it out without much guidance youre welcome to work on it

**Comment by eshack94** [comment]
Sounds good. I'm working on it now, thanks for the tips. I'll try and get a PR ready for submission this week sometime.

So far I've made changes to `index.js` and `interfaces.js`. Next I need to figure out the changes to make to each of the providers files. I'm also thinking about adding a toggle for the dark mode setting.

It looks like the providers handle the custom CSS for each of the providers, while `index.css` handles the CSS for the app menubar app itself? So it looks like I _won't_ need to make changes to `index.css`, but please correct me if I'm wrong.

Progress report:

<img width="540" alt="in-progress" src="https://github.com/smol-ai/menubar/assets/33649649/16d95aca-7bfc-4ee6-9e43-273353018dd1">

**Comment by eshack94** [comment]
Opened WIP PR and linked to this issue for visibility. I could use some help figuring out where to find the provider-specific dark mode changes that get made when users enable dark mode for each. I assume that info is available within browser DevTools somewhere, but I'm not sure where to find it.

I'll work more on this PR later this week when I have some free time.

**Comment by swyxio** [comment]
> It looks like the providers handle the custom CSS for each of the providers, while index.css handles the CSS for the app menubar app itself? So it looks like I won't need to make changes to index.css, but please correct me if I'm wrong.

correct

**Comment by swyxio** [comment]
this was added in #107 

but still not very stable yet i think. needs a bit more testing
